on:
  push:
  repository_dispatch:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - if: false       # always skip to prevent DDoSing ourselves!
      name: This should be skipped
      run: echo "You've messed up."
